# Internal timings
set(ASYNC_POLL_LOOP_MS 60 CACHE INTERNAL "")
set(CONTROL_PANEL_BLINK_INTERVAL_MS 60 CACHE INTERNAL "")
set(CONTROL_PANEL_FLASH_SHORT_ON_MS 20 CACHE INTERNAL "")
set(CONTROL_PANEL_FLASH_SHORT_OFF_MS 30 CACHE INTERNAL "")
set(CONTROL_PANEL_FLASH_LONG_ON_MS 40 CACHE INTERNAL "")
set(CONTROL_PANEL_FLASH_LONG_OFF_MS 50 CACHE INTERNAL "")
set(ERROR_EVENT_SLEEP_MS 60 CACHE INTERNAL "")
set(ERROR_EVENT_REBOOT_MS 120 CACHE INTERNAL "")