#ifndef _APP_MONITOR_H
#define _APP_MONITOR_H

enum app_monitor_event { 
    APP_MONITOR_OFF_BUTTON, 
    APP_MONITOR_AUTO_BUTTON,
    APP_MONITOR_ON_BUTTON,
    APP_MONITOR_CURRENT_ON,
    APP_MONITOR_CURRENT_OFF
};

#endif